language: csharp
mono: latest
script:
  - VERSION=$(grep -o -m 1 "[0-9]\+.[0-9]\+.[0-9]\+" CHANGELOG.md)
  - sed -e 's/#.#.#/'${VERSION}'/g' -i CSharp.Styleguide.targets
  - nuget pack CSharp.Styleguide.nuspec -Version $VERSION
before_deploy:
  - curl https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -o nuget.exe -s
deploy:
  provider: script
  skip_cleanup: true
  script:
    - mono nuget.exe push CSharp.Styleguide.$VERSION.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey $NUGET_API_KEY -NonInteractive
  on:
    branch: master
env:
  global:
    secure: KI0XCo8+DuOUMBS86HrakZRY07BqxAjReDzAbEsCjBgeFJchCuEicT8itIp2nm99nFESchaP+usH5S1LoHDCES0Q8P8d2H/I81upmV5OTDqpu444mnisJFbfrHEpk9nNdsXbOJqIYqp+aDxcfuoibUpUZfVXXwZQ5V8mngHuiHZS5Rup2LmeKVJ9Z6ci62ZSFzxWK1lj1eZbGY5TVOs+XIyBzaL4qCXaBAQKbQ4UtSrb4ToE60pfKwXDI6yUOTHymBgk5RpzDJoxpfbkP03iPEitaV19Nh0/1Ax5h8xs+ronSdeJ8iuw2MSZTcgvxoeiB9GnrzBkSZHnIYmO7Im6ve8EVOGWKwgHasCDJ8Rj06G2VluDSSCVW5OR5vFQ45QfouXrfLsIka4ExeOW5+GgL5ZKIbf+ssOwdnCEJyyLY2BLKn4Ncf5fh/ddiRAVVwKxQquXLY4+Jaqn/PVm70C62tsJ/GzRXGv6qsmpuY/AjsZ3aeQq6BezqUwkaVePfzJYe39SX7a3GLO0nxle8DaNKZMU1m9LrPdVpIOojQpgWZuNAsa2Oq850Gn3h8Sw+I0T9D+gHVZxs1WU9BnNqmkVc3HuPiv0YuwUVetl23q8g4bHfrdKF9VfyAF9BJc/MPEOHQgq36VRgS8xjjaLGst9a7jRPWDQq7nLKXNECKsT3dM=
